import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full bg-orange-500 flex justify-between px-16 py-6">
          <h1 className="font-semibold">SMIT CARD PRINTER</h1>

          <div className="gap-10 flex">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
          </div>
        </div>

        {children}

        <div className="w-full bg-slate-600">
          <p className="pt-32 pb-6 text-xl text-white text-center">
            All right reserved SMIT@{new Date().getFullYear()}
          </p>
        </div>
      </body>
    </html>
  );
}
